name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x # Adjust node version as needed

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            xvfb-run -a npm test
          else
            npm test
          fi

      - name: Publish Extension
        if: success() && matrix.os == 'ubuntu-latest'
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          PUBLISHER_NAME: ${{ secrets.PUBLISHER_NAME }}
        run: |
          npm install -g vsce
          vsce login $PUBLISHER_NAME --pat $VSCE_PAT
          vsce package
          vsce publish minor
